#configmap for mongodb
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  #üsttekini -name yazıp env'e koyucaz deployment.yaml'da yapınca alta yıldız koy
  #yapınca yıldız koy
stringData:
  MONGO_INITDB_ROOT_USERNAME: "beyto"
  MONGO_INITDB_ROOT_PASSWORD: "Beyto1905."
