replicaCount: 1
tier: frontend

image:
  repository: "webapp"
  tag: "v1"
  #pullPolicy: IfNotPresent bu lazım değil v1 var bizde !!

service:
  type: ClusterIP
  port: 5000

configMap:
    DB: "mydb" 
    #url complex sonra çözeceğim


ingress:
  host: webapp.local
  className: nginx
  path: /

# # enabled: false