apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
#    labels:
#        app: {{ .Release.Name }}-webapp
spec:
  accessModes:
    - ReadWriteOnce #bir nod okuma yazma yapabilir
  storageClassName: {{ .Release.Name }}-sc
  resources:   
    requests:
      storage: {{ .Values.storage.size }} #values'a yaz kaç Gi