#deployment file for webapp 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp-deployment
  labels:
    app: {{ .Release.Name }}-webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webapp
  
  template:
    metadata:
      name: {{ .Release.Name }}-webapp
      labels:
        app: {{ .Release.Name }}-webapp
        tier: frontend
    spec:
      containers:
        - name: webapp
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
          
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-webapp-configmap
