replicaCount: 1

image:
  repository: "webapp"
  tag: "v1"
  #pullPolicy: IfNotPresent bu lazım değil v1 var bizde !!
  targetPort: 5000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

configMap:
    DB: "mydb" 
    #url complex sonra çözeceğim


ingress:
  host: webapp.local


# # enabled: false

