apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PVC.name }} 
#    labels:
#        app: {{ .Release.Name }}-webapp
spec:
  accessModes:
    - ReadWriteOnce #bir nod okuma yazma yapabilir
  storageClassName: {{ .Values.storage.className }} #values'a yaz
  resources:   
    requests:
      storage: {{ .Values.storage.size }} #values'a yaz kaç Gi yaz