# Storage for webapp
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: {{ .Values.storage.provisioner }}
#işi yapan csi her path için farklı provisioner var minikube-hostpath bizimki 
#parameters:
#  type: ???
#  fstype: ??? GEREK YOK LOCAL için bu ayarlamalara

reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
