flask-mongo: 
  image:
    repository: "webapp"
    tag: "v1"
    targetPort: 5000
  replicaCount: 2 

    
mongodb:
  image:
    repository: "mongo"
    tag: "latest"
    targetPort: 27017
  replicaCount: 1

releaseName: "myrelease"
