name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  helm:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v5
      with:
        version: v3.18.4
    - name: Install Helm dependencies
      run: helm dependency update webapp
    - name: Lint Helm chart
      run: helm lint webapp
